# AI Agentic Workflow Launchpad Configuration
# Main configuration file with environment variable substitution support

# Application Settings
app_name: "AI Agentic Workflow Launchpad"
version: "1.0.0"
environment: "${ENVIRONMENT:development}"
debug: ${DEBUG:false}

# Default LLM Provider
default_llm: "openai"

# LLM Client Configurations
llm_clients:
  openai:
    provider: "openai"
    model: "${OPENAI_MODEL:gpt-3.5-turbo}"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.7
    max_tokens: 2000
    timeout: 30
  
  anthropic:
    provider: "anthropic"
    model: "${ANTHROPIC_MODEL:claude-3-sonnet-20240229}"
    api_key: "${ANTHROPIC_API_KEY}"
    temperature: 0.7
    max_tokens: 2000
    timeout: 30
  
  gemini:
    provider: "gemini"
    model: "${GEMINI_MODEL:gemini-pro}"
    api_key: "${GEMINI_API_KEY}"
    temperature: 0.7
    max_tokens: 2000
    timeout: 30

# Agent Configurations
agents:
  router:
    name: "Router Agent"
    description: "Routes user requests to appropriate task agents"
    llm_provider: "openai"
    system_prompt: "You are a router agent responsible for analyzing user requests and determining which specialized agent should handle the task."
    temperature: 0.3
    max_iterations: 5
    tools: []
  
  task_agent_1:
    name: "Calculator Agent"
    description: "Mathematical calculator agent with step-by-step reasoning"
    llm_provider: "openai"
    system_prompt: "You are a mathematical calculator assistant that explains calculations step-by-step."
    temperature: 0.3
    max_iterations: 10
    tools: ["calculator"]
  
  task_agent_2:
    name: "Task Agent 2"
    description: "Handles complex reasoning and planning tasks"
    llm_provider: "openai"
    system_prompt: "You are a specialized agent for complex reasoning, planning, and strategic thinking."
    temperature: 0.5
    max_iterations: 15
    tools: ["planning", "analysis", "reasoning"]

# Workflow Configurations
workflows:
  sequential:
    name: "Sequential Workflow"
    description: "Execute agents in sequential order"
    type: "sequential"
    agents: ["router", "task_agent_1", "task_agent_2"]
    max_steps: 20
    timeout: 300
  
  collaborative:
    name: "Collaborative Workflow"
    description: "Agents collaborate on complex tasks"
    type: "collaborative"
    agents: ["task_agent_1", "task_agent_2"]
    max_steps: 25
    timeout: 600
  
  router_workflow:
    name: "Intelligent Router Workflow"
    description: "Router intelligently routes tasks to appropriate agents"
    type: "router_based"
    agents: ["router"]
    max_steps: 30
    timeout: 450

# Logging Configuration
logging:
  level: "${LOG_LEVEL:DEBUG}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "${LOG_FILE_PATH:logs/app.log}"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Performance Settings
max_concurrent_agents: ${MAX_CONCURRENT_AGENTS:5}
request_timeout: ${REQUEST_TIMEOUT:30}
retry_attempts: ${RETRY_ATTEMPTS:3} 